type: http
name: Get identity and application provisioning status
url: '{{baseUrl}}/workers/:workerId/provisioning-status'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: workerId
    value: 2831a0c1-26b5-8f21-9b30-2d795eedcb9f
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "workerId": "2a300580-1493-939f-def8-30685fe3cc6a",
            "identityStatus": "in_progress",
            "laptopStatus": "completed",
            "applicationAccess": [
              {
                "systemName": "string",
                "status": "failed"
              },
              {
                "systemName": "string",
                "status": "failed"
              }
            ]
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Provisioning state
