type: http
name: Get identity and application provisioning status
url: '{{baseUrl}}/workers/:workerId/provisioning-status'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: workerId
    value: 061f3bb9-b6c0-1fc8-bb63-ba756c2f4f71
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "workerId": "13630181-6e29-00bd-e7d8-0c4625190613",
            "identityStatus": "failed",
            "laptopStatus": "in_progress",
            "applicationAccess": [
              {
                "systemName": "string",
                "status": "not_started"
              },
              {
                "systemName": "string",
                "status": "completed"
              }
            ]
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Provisioning state
