type: http
name: Get identity and application provisioning status
url: '{{baseUrl}}/workers/:workerId/provisioning-status'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: workerId
    value: ac96d861-8325-9a2a-3c85-1b0571174b7e
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "workerId": "a64c5e06-d3c6-5246-94b4-f972be32b78f",
            "identityStatus": "completed",
            "laptopStatus": "completed",
            "applicationAccess": [
              {
                "systemName": "string",
                "status": "completed"
              },
              {
                "systemName": "string",
                "status": "failed"
              }
            ]
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Provisioning state
