type: http
name: Trigger an automation run for a given suite and environment
url: '{{baseUrl}}/test-runs'
method: POST
headers:
  - key: Content-Type
    value: application/json
  - key: Accept
    value: application/json
body:
  type: json
  content: |-
    {
      "suiteId": "889b39bd-fb3f-6ee6-f2f9-1b8fc8a715f7",
      "environment": "preprod",
      "releaseVersion": "string",
      "triggeredBy": "string",
      "runMode": "regression"
    }
examples:
  - response:
      statusCode: 201
      statusText: Created
      body:
        type: json
        content: |-
          {
            "runId": "d8eeb4d0-f779-082c-0387-7e1d39964715",
            "suiteId": "d48e87de-94b1-8a33-1368-c77ab14e637f",
            "status": "queued",
            "environment": "string",
            "releaseVersion": "string",
            "startedAt": "1999-01-15T17:12:33.254Z",
            "finishedAt": "2010-02-20T10:40:34.292Z",
            "passedCount": 2959,
            "failedCount": 3460,
            "flakyCount": 3372
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Test run started
