type: http
name: Trigger an automation run for a given suite and environment
url: '{{baseUrl}}/test-runs'
method: POST
headers:
  - key: Content-Type
    value: application/json
  - key: Accept
    value: application/json
body:
  type: json
  content: |-
    {
      "suiteId": "cd680391-430e-db01-4862-0f4a4b662260",
      "environment": "uat",
      "releaseVersion": "string",
      "triggeredBy": "string",
      "runMode": "smoke"
    }
examples:
  - response:
      statusCode: 201
      statusText: Created
      body:
        type: json
        content: |-
          {
            "runId": "62a3cb15-0cf8-cf47-334c-7fdb5cfbe204",
            "suiteId": "b9b6b242-c756-16a0-49ad-ff4e53eb40ae",
            "status": "running",
            "environment": "string",
            "releaseVersion": "string",
            "startedAt": "2007-04-07T12:44:39.013Z",
            "finishedAt": "1993-10-25T12:58:23.447Z",
            "passedCount": 8144,
            "failedCount": 1347,
            "flakyCount": 1711
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Test run started
