type: http
name: Trigger an automation run for a given suite and environment
url: '{{baseUrl}}/test-runs'
method: POST
headers:
  - key: Content-Type
    value: application/json
  - key: Accept
    value: application/json
body:
  type: json
  content: |-
    {
      "suiteId": "142ebfa8-d745-67c9-6b39-1daab1553448",
      "environment": "uat",
      "releaseVersion": "string",
      "triggeredBy": "string",
      "runMode": "full"
    }
examples:
  - response:
      statusCode: 201
      statusText: Created
      body:
        type: json
        content: |-
          {
            "runId": "631080d8-b1be-53cb-0575-f4b93a33e9a6",
            "suiteId": "ed50ed9d-e5f8-c601-c636-fc3b832807f3",
            "status": "passed",
            "environment": "string",
            "releaseVersion": "string",
            "startedAt": "2002-10-01T00:07:59.830Z",
            "finishedAt": "1955-11-20T15:46:31.638Z",
            "passedCount": 3882,
            "failedCount": 8068,
            "flakyCount": 7987
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Test run started
